# This file was generated by GoReleaser. DO NOT EDIT.
cask "hippocamp" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_darwin_amd64.tar.gz"
      sha256 "c2e927e829ec12c58999dfeb24c9224d3edad88c4a2c4348e86cb390162c119e"
    end
    on_arm do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_darwin_arm64.tar.gz"
      sha256 "2706f21353487cc4041fe94524f3d47fc1b6d26e4ee01c7c145de3911e4d1e6d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_linux_amd64.tar.gz"
      sha256 "f99c2b3b6ab585e633f71b83c2ee5a8a1414bd420829adf06fe97f7146c2858e"
    end
    on_arm do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_linux_arm64.tar.gz"
      sha256 "b4132d7a81ee369c673a4f55f2086aa8cb2d7bd1c23cdc6c144d4861a82d9ed6"
    end
  end

  name "hippocamp"
  desc "RDF MCP server — expose an in-memory knowledge graph to LLMs via triple/sparql/graph tools"
  homepage "https://github.com/tggo/hippocamp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hippocamp"

  # No zap stanza required

end
