# This file was generated by GoReleaser. DO NOT EDIT.
cask "hippocamp" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_darwin_amd64.tar.gz"
      sha256 "452194f2dc72deaa68ac61a59b615d968f0484a5dfe4b0936cfcdd36d62f58b5"
    end
    on_arm do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_darwin_arm64.tar.gz"
      sha256 "66f72c82f5e71c8c97e10fa7895f1ff463e80ab1d0d53ff1de462395da988804"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_linux_amd64.tar.gz"
      sha256 "1aa27a1bea1f8380e684d843a7293c5ec82ec10156f97df1f507156e219b2302"
    end
    on_arm do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_linux_arm64.tar.gz"
      sha256 "504bb81620424ad7491745e4a6c9d7b07fb4188b08b5374587ba61d83673f2e6"
    end
  end

  name "hippocamp"
  desc "RDF MCP server — expose an in-memory knowledge graph to LLMs via triple/sparql/graph tools"
  homepage "https://github.com/tggo/hippocamp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hippocamp"

  # No zap stanza required

end
