# This file was generated by GoReleaser. DO NOT EDIT.
cask "hippocamp" do
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_darwin_amd64.tar.gz"
      sha256 "79100c7af3c70358bd05fad85e7aea47e83328c72f2808f95bfdf769518458f9"
    end
    on_arm do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_darwin_arm64.tar.gz"
      sha256 "666c9f7f997ed0fb5e006392def061f5fe01b65b240635e4c39b6e07e93a4788"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_linux_amd64.tar.gz"
      sha256 "7551ca48e94a677e975c7e6e6b60a26413c026879ec507bbd49ed413f3be4fad"
    end
    on_arm do
      url "https://github.com/tggo/hippocamp/releases/download/v#{version}/hippocamp_linux_arm64.tar.gz"
      sha256 "a623ebeceda60b5261e03f8b2d1b7b5da6601d1a5c964ecf6c58cef46059a902"
    end
  end

  name "hippocamp"
  desc "RDF MCP server — expose an in-memory knowledge graph to LLMs via triple/sparql/graph tools"
  homepage "https://github.com/tggo/hippocamp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hippocamp"

  # No zap stanza required

end
